# Swagger 2.0 demo used in the REST API Course
# http://www.acloudfan.com
# Part 1 of the incremental creation of the swagger for
# Vacations API for the fictitious enterprise "ACME Travels"

# Swagger 2.0 always begin with the following
swagger: "2.0"

########### Part 1 ###########

# git checkout  rootdocument
# to check the content in part-1

########### Part 2 ########

# git checkout  definitions
# to check the content in part-2

########### Part 3 ########

# git checkout  paths
# to check the content in part-3

########### Final Swagger ###

# git checkout  final
# to check the content for final state of the swagger